package org.cevahir.alumni.model;

// Generated 29-Jun-2008 12:22:55 by Hibernate Tools 3.2.2.GA

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Year generated by hbm2java
 */
@Entity
@Table(name = "year", catalog = "alumni")
public class Year extends Model implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8203964991175448226L;
	private int id;
	private Serializable year;

	public Year() {
	}

	public Year(int id, Serializable year) {
		this.id = id;
		this.year = year;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "year", nullable = false)
	public Serializable getYear() {
		return this.year;
	}

	public void setYear(Serializable year) {
		this.year = year;
	}

}
